BibliotecaFSJ/Controllers/ChatController.cs
using BibliotecaFSJ.DAO.DAO;
using BibliotecaFSJ.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BibliotecaFSJ.Controllers
{
    public class ChatController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public ChatController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> CaixaEntrada(string idUsuario)
        {
            var result = await MensagensDAO.GetConversasByUsuario(idUsuario);

            List<ConversaListaViewModel> model = new List<ConversaListaViewModel>();

            foreach(var conversa in result)
            {
                var ultimaMsg = conversa.Mensagens.OrderBy(x => x.Envio).LastOrDefault();

                model.Add(new ConversaListaViewModel
                {
                    Id = conversa.Id,
                    ConteudoUltimaMensagem = ultimaMsg.Conteudo,
                    DataUltimaMensagem = ultimaMsg.Envio.ToString("dd/MM/yyyy HH:mm"),
                    NomeUsuario = _userManager.FindByIdAsync(ultimaMsg.IdRemetente).Result.UserName
                });
            }

            return View(model);
        }

        public async Task<IActionResult> Enviados(string idUsuario)
        {
            var result = await MensagensDAO.GetConversasEnviadasByUsuario(idUsuario);

            List<ConversaListaViewModel> model = new List<ConversaListaViewModel>();

            foreach(var conversa in result)
            {
                var ultimaMsg = conversa.Mensagens.OrderBy(x => x.Envio).LastOrDefault();

                model.Add(new ConversaListaViewModel
                {
                    Id = conversa.Id,
                    ConteudoUltimaMensagem = ultimaMsg.Conteudo,
                    DataUltimaMensagem = ultimaMsg.Envio.ToString("dd/MM/yyyy HH:mm"),
                    NomeUsuario = _userManager.FindByIdAsync(ultimaMsg.IdDestinatario).Result.UserName
                });
            }

            return View(model);
        }

        public async Task<IActionResult> Mensagens(long idConversa)
        {
            List<MensagemListaViewModel> model = new List<MensagemListaViewModel>();

            var mensagens = await MensagensDAO.GetMensagensByConversa(idConversa);

            foreach (var msg in mensagens)
            {
                model.Add(new MensagemListaViewModel { 
                    Id = msg.Id,
                    ConteudoMensagem = msg.Conteudo,
                    IdConversa = msg.ConversaId,
                    IdRemetente = msg.IdRemetente,
                    DataMensagem = msg.Envio.ToString("dd/MM/yyyy mm:HH"),
                    NomeRemetente = _userManager.FindByIdAsync(msg.IdRemetente).Result.UserName
                });

                var queryDestinatario = mensagens.Where(x => x.IdRemetente != _userManager.GetUserId(User)).ToList();

                ViewBag.Destinatario = queryDestinatario.Count > 0 ? queryDestinatario.First().IdRemetente : null;

                if(ViewBag.Destinatario == null)
                {
                    queryDestinatario = mensagens.Where(x => x.IdDestinatario != _userManager.GetUserId(User)).ToList();

                    ViewBag.Destinatario = queryDestinatario.Count > 0 ? queryDestinatario.First().IdRemetente : null;
                }

                ViewBag.IdConversa = idConversa;
            }

            return View(model);
        }
    }
}

BibliotecaFSJ/Controllers/PerfilController.cs
using BibliotecaFSJ.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace BibliotecaFSJ.Controllers
{
    public class PerfilController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;

        public PerfilController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        public async static Task<string> GetUserNameById(string id, UserManager<IdentityUser> manager)
        {
            var usuario = await manager.FindByIdAsync(id);
            return usuario.UserName;
        }

        public async Task<IActionResult> MinhaConta(string id)
        {
            if (string.IsNullOrEmpty(id))
                return NotFound();

            var usuario = await _userManager.FindByIdAsync(id);

            var model = new ContaViewModel()
            {
                Id = id,
                Nome = usuario.NormalizedUserName,
                Usuario = usuario.UserName,
                Email = usuario.Email
            };

            if (TempData["msg"] != null)
                ViewBag.Msg = TempData["msg"];

            return View(model);
        } 
        
        [HttpPost]
        public async Task<IActionResult> MinhaConta(ContaViewModel model, IFormFile file)
        {
            var usuario = await _userManager.FindByIdAsync(model.Id);

            if (usuario == null)
                return NotFound();

            usuario.Email = model.Email;
            usuario.UserName = model.Usuario;
            usuario.NormalizedUserName = model.Nome;

            await _userManager.UpdateAsync(usuario);

            if(file != null) 
                await SalvaFoto(usuario.Id,file);

            TempData["msg"] = "Perfil atualizado";
            return RedirectToAction("MinhaConta", new { id = model.Id });
        }

        async Task<bool> SalvaFoto(string userId, IFormFile file)
        {
            try
            {
                var fileName = userId + "." + file.FileName.Split('.')[1];
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Imagens\User", fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
                return true;
            }
            catch
            {
                return false;
            }
        }
    }
}

BibliotecaFSJ/Views/Shared/_AutenticacaoLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  Fórum FSJ</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BibliotecaFSJ/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]   Fórum FSJ</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        function handeInputPesquisa()
        {
            $("#linkPesquisa").attr("href", "/Home/Pesquisa?query=" + $("#inputPesquisa").val())
        }
    </script>

    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fórum FSJ</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item row">
                            <div class="input-group">
                                <input class="form-control form-control-sm" type="search" placeholder="Pesquisar assuntos" id="inputPesquisa" onchange="handeInputPesquisa()">
                                <div class="input-group-append ml-2">
                                    <a href="/Home/Pesquisa?query=" id="linkPesquisa" class="rounded btn btn-primary text-white "><i class="fas fa-search"></i></a>
                                </div>
                            </div>
                            
                        </li>
                    </ul>
                </div>
                <div class="dropdown">
                    <img class="imagem" style="border-radius: 50%; width: 45px; height: 45px;" src='@string.Concat("/Imagens/User/",UserManager.GetUserId(User),".jpg")' alt="~/Imagens/usericon.jpg" />

                    <span class="m-2">@UserManager.GetUserName(User)</span>
                    <div class="dropdown-content text-center">
                        <a href="@Url.Action("CaixaEntrada","Chat",new { idUsuario = UserManager.GetUserId(User) })" class="btn btn-outline-secondary mt-2 mb-2">Mensagens</a>
                        @Html.ActionLink("Minha conta", "MinhaConta", "Perfil", new { id = UserManager.GetUserId(User) }, new { @class = "btn btn-outline-secondary" })
                        @Html.ActionLink("Sair", "Sair", "Autenticacao", new { }, new { @class = "btn btn-outline-danger mt-2 mb-2" })
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Fórum FSJ
        </div>
    </footer>
</body>
</html>