BibliotecaFSJ/Controllers/HomeController.cs
using BibliotecaFSJ.DAO.DAO;
using BibliotecaFSJ.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Linq;

namespace BibliotecaFSJ.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var obj = TopicoDAO.GetPaginaInicial().GroupBy(x => x.Id).Select(x => x.First()).ToList();

            return View(obj);
        }

        public IActionResult Pesquisa(string query)
        {
            var obj = TopicoDAO.GetPesquisa(query).GroupBy(x => x.Id).Select(x => x.First()).ToList();

            return View(obj);
        }
    }
}

BibliotecaFSJ/Controllers/TopicoController.cs
using BibliotecaFSJ.DAO.DAO;
using BibliotecaFSJ.Models;
using BibliotecaFSJ.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace BibliotecaFSJ.Controllers
{
    public class TopicoController : Controller
    {
        public async Task<IActionResult> Exibir(int topicoId)
        {
            Topico topico = await TopicoDAO.GetById(topicoId);
            topico.Tags = TagDAO.GetByTopico(topicoId);

            TopicoViewModel model = new TopicoViewModel
            {
                Id = topicoId,
                Texto = topico.Texto,
                Titulo = topico.Titulo,
                Tags = new List<string>(),
                Imagens = new List<string>(),
                Comentarios = new List<Comentario>()
            };

            if(topico.Tags != null)
                topico.Tags.ToList().ForEach(x => { model.Tags.Add(x.Texto); });

            var imagens = await ImagemTopicoDAO.GetTopicoImagensByTopicoId(topicoId);

            if(imagens != null)
                imagens.ForEach(x => { model.Imagens.Add(x.Url); });

            model.Comentarios = await ComentarioDAO.GetComentariosByTopico(topico.Id);

            return View(model);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Criar(TopicoViewModel model)
        {
            var imagens = Request.Form.Files.ToList();
            model.Tags = model.Tags[0].Split(',').ToList();

            Topico topico = new Topico
            {
                Texto = model.Texto,
                Titulo = model.Titulo
            };

            var result = await TopicoDAO.Gravar(topico);

            List<Tag> tags = new List<Tag>();

            foreach (string tag in model.Tags)
            {
                tags.Add(new Tag { Texto = tag, TopicoId = topico.Id });
            }

            var resultTag = await TagDAO.Gravar(tags);

            //depois de gravar o topico e as tags, grava as imagens
            bool resultFoto = false;

            if (imagens.Count > 0)
                resultFoto = await SalvaFoto(topico.Id, imagens);
            else
                resultFoto = true;

            if (result && resultTag && resultFoto)
                return RedirectToAction(nameof(Exibir), new { topicoId = topico.Id });

            return BadRequest();
        }

        async Task<bool> SalvaFoto(int topicoId, List<IFormFile> files)
        {
            try
            {
                int i = 0;
                List<TopicoImagens> objs = new List<TopicoImagens>();

                foreach(var file in files)
                {
                    var fileName = topicoId + i + "." + file.FileName.Split('.')[1];
                    Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Imagens\Topico", topicoId.ToString()));
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Imagens\Topico", topicoId.ToString(), fileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(fileStream);


                        objs.Add(new TopicoImagens { TopicoId = topicoId, Url = Path.Combine(@"\Imagens\Topico", topicoId.ToString(), fileName) });
                    }
                    i++;
                }
                
                return await ImagemTopicoDAO.SalvarImagensTopico(objs);
            }
            catch(Exception e)
            {
                return false;
            }
        }
    }
}

BibliotecaFSJ/Views/Home/Index.cshtml
@model List<Topico>
@using System.Text.RegularExpressions;

<div class="row">
    <div class="col-auto mt-2">
        <div class="card shadow-lg border-success" style="width: 15rem;height: 15rem">
            <div class="card-body">
                <div class="text-center">
                    <h5 class="card-title">
                        Criar tópico
                    </h5>
                </div>
                <p class="text-justify text-center pt-4">Crie um tópico e converse com as pessoas sobre o assunto que desejar.</p>
            </div>
            <div class="card-footer">
                <div class="text-center">
                    @Html.ActionLink("Começar", "Criar", "Topico", new { }, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>
    </div>
    @if (Model != null)
    {
        @foreach (var topico in Model)
        {
            //@if (topico.Texto.Length > 20) topico.Texto = Html.Raw(topico.Texto.Substring(20)).ToString();

            <div class="col-auto mt-2">
                <div class="card shadow-lg" style="width: 15rem;height: 15rem">
                    <div class="card-body">
                        <div class="text-center">
                            <h5 class="card-title text-truncate d-inline-block" style="max-width: 250px;">
                                @topico.Titulo
                            </h5>
                        </div>
                        @if (Regex.Replace(topico.Texto, "<.*?>",String.Empty).Length > 110)
                        {
                            <text><p class="text-justify" style="max-width: 255px; max-height:100px;">@Regex.Replace(topico.Texto, "<.*?>",String.Empty).Substring(0,110).Replace("Powered by Froala Editor","") ...</p></text>
                        }
                        else
                        {
                            <p class="text-justify" style="max-width: 255px; max-height:100px;">@Regex.Replace(topico.Texto, "<.*?>",String.Empty).Replace("Powered by Froala Editor","")</p>
                        }
                    </div>
                    <div class="card-footer">
                        <div class="text-center">
                            @Html.ActionLink("Ver", "Exibir", "Topico", new { topicoId = topico.Id }, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>

BibliotecaFSJ/Views/Home/Pesquisa.cshtml
@model List<Topico>
@using System.Text.RegularExpressions;

@{
    ViewData["Title"] = "Pesquisa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@if (Model != null && Model.Count > 0)
{
    <div class="row">

        @foreach (var topico in Model)
        {

            <div class="col-auto mt-2">
                <div class="card shadow-lg" style="width: 15rem;height: 15rem">
                    <div class="card-body">
                        <div class="text-center">
                            <h5 class="card-title text-truncate d-inline-block" style="max-width: 250px;">
                                @topico.Titulo
                            </h5>
                        </div>
                        <p class="text-justify" style="max-width: 255px; max-height:100px;">@Regex.Replace(topico.Texto, "<.*?>", String.Empty).Substring(0, 110) ...</p>
                    </div>
                    <div class="card-footer">
                        <div class="text-center">
                            @Html.ActionLink("Ver", "Exibir", "Topico", new { topicoId = topico.Id }, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
            </div>

        }
    </div>
}
else
{
    <p class="alert alert-warning text-black text-center">Oops ! Não foi encontrado nenhum resultado &#128533;</p>
}